            - name: Cache
  uses: actions/cache@v4.2.0
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false
    # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    lookup-only: # optional, default is false
    # Run the post step to save the cache even if another step before fails
    save-always: # optional, default is false
          name: Football Blog Workflow

on:
  # Trigger workflow on push to blog content directory
  push:
    paths:
      - 'content/football/**'
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      title:
        description: 'Blog post title'
        required: true
      author:
        description: 'Author name'
        required: true
        default: 'Editorial Team'

jobs:
  create-blog-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies if using a static site generator
      - name: Install dependencies
        run: npm install

      # Create new blog post from template
      - name: Create blog post
        run: |
          POST_DATE=$(date +"%Y-%m-%d")
          POST_SLUG=$(echo "${{ github.event.inputs.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
          
          cat << EOF > content/football/$POST_DATE-$POST_SLUG.md
          ---
          title: "${{ github.event.inputs.title }}"
          date: $POST_DATE
          author: "${{ github.event.inputs.author }}"
          category: "Football"
          tags: ["football", "sports"]
          draft: true
          ---

          [Your football blog content goes here]
          EOF

      # Optional: Run content validation
      - name: Validate content
        run: |
          # Add your content validation logic here
          # Example: Check for minimum word count, required sections, etc.
          echo "Validating content structure and requirements"

      # Build the blog if using a static site generator
      - name: Build blog
        run: npm run build

      # Create pull request with new content
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "New Football Blog Post: ${{ github.event.inputs.title }}"
          body: |
            New football blog post created via automated workflow.
            
            Please review the content and merge when ready.
            
            - Title: ${{ github.event.inputs.title }}
            - Author: ${{ github.event.inputs.author }}
            - Date: ${{ env.POST_DATE }}
          branch: "blog/football-${{ github.sha }}"
          commit-message: "Add new football blog post: ${{ github.event.inputs.title }}"
          labels: "content,needs-review"

      # Optional: Notify team about new blog post
      - name: Notify team
        if: success()
        run: |
          echo "New blog post created successfully"
          # Add notification logic (e.g., Slack, email) here
